name: QA Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  skai-prod:
    name: Playwright — Skai PROD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: Playwright/skai-wp-regression-tests
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run tests
        working-directory: Playwright/skai-wp-regression-tests
        run: npx playwright test


  skai-dev:
    name: Playwright — Skai DEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: Playwright/skai-DEV-wp-regression-tests
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run tests
        working-directory: Playwright/skai-DEV-wp-regression-tests
        run: npx playwright test


  cymulate-prod:
    name: Playwright — Cymulate PROD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: Playwright/cymulate-wp-regression-tests
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run tests
        working-directory: Playwright/cymulate-wp-regression-tests
        run: npx playwright test


  cymulate-dev:
    name: Playwright — Cymulate DEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: Playwright/cymulate-DEV-wp-regression-tests
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run tests
        working-directory: Playwright/cymulate-DEV-wp-regression-tests
        run: npx playwright test
